# 作者：岑忠满
# 日期：2018年12月3日
# 功能：jenkins-BlueOcean
# 说明：建议用户名使用root(必须为Docker用户组)，挂载的.m2路径也需要相同用户名

version: '3'
services:
  jenkins:
    image: jenkinsci/blueocean:1.9.0
    restart: always
    user: root
    ports:
      - 8081:8080
    volumes:
      - jenkins:/var/jenkins_home
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /var/run/docker.sock:/var/run/docker.sock

volumes: 
  jenkins:
    external: true    